version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@100
      POSTGRES_DB: "my_ticket_db"
      TZ: "America/Sao_Paulo"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis/redis-stack
    restart: always
#    environment:
#      REDIS_ARGS: extra arguments for Redis
#      REDISEARCH_ARGS: arguments for RediSearch
#      REDISJSON_ARGS: arguments for RedisJSON
#      REDISGRAPH_ARGS: arguments for RedisGraph
#      REDISTIMESERIES_ARGS: arguments for RedisTimeSeries
#      REDISBLOOM_ARGS: arguments for RedisBloom
    volumes:
      - ./database/redis:/data
    ports:
      - 6379:6379
      - 9091:8001
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    depends_on:
      - postgres
