apps:
  - script: ./dist/server.js
    name: 'AthonAPI'
    watch: true
    instances: 0
    exec_mode: cluster
    env:
      NODE_ENV: process.env.NODE_ENV,
      DB_CLIENT: process.env.DB_CLIENT,
      DB_HOST: process.env.DB_HOST,
      DB_NAME: process.env.DB_NAME,
      DB_USER: process.env.DB_USER,
      DB_PASSWORD: process.env.DB_PASSWORD,
      DB_PORT: process.env.DB_PORT,
      PORT: process.env.PORT,
      REDISHOST: process.env.REDISHOST;
      REDISPORT: process.env.REDISPORT;
      SERVER_HOST: process.env.SERVER_HOST,
      SALT_ROUNDS: process.env.SALT_ROUNDS,
      AUTHSECRET: process.env.AUTHSECRET
